[env:nano_33_iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 9600

lib_deps =
	adafruit/Adafruit NeoPixel @ ^1.12.3
	adafruit/Adafruit seesaw Library @ ^1.7.7
	adafruit/Adafruit BusIO @ ^1.16.1
	mathertel/RotaryEncoder @ ^1.5.3
	WiFiNINA
	knolleary/PubSubClient @ ^2.8
